export const
    keymessage = {
        rejectdate: 'Fecha de rechazo',
        salesunit: 'Unidad de venta',
        reason: 'Tipo de rechazo',
        comentario: 'Comentario',
        creation_date: "Fecha creación",
        creation_user: "Usuario creación",
        delivery: "Número de entregra",
        drivercc: "Cédula conductor",
        drivername: "Nombre conductor",
        last_update: "última actualización",
        licenseplate: "Placa del vehículo",
        loadid: "Número de carga",
        loadorderid: "Número de orden",
        originlocationid: "Id. localización del origen",
        reg_status: "Estado",
        totaldeliverycount: "Total entregas",
        totalpiecessum: "Total piezas",
        totalvolumesum: "Total volumen",
        totalweightsum: "Total peso",
        user_update: "Usuario actualización",
        vehicletype: "Tipo de vehículo",
        accessorytype: "Tipo del accesorio",
        quantity: "Cantidad del accessorio",
        requestdate: "Fecha del pedido",
        costoverrun: "Valor del sobre costo",
        comentarios: "Comentarios",
    };